/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import forme.iznajmljivanje.KreirajIznajmljivanje;
import forme.prodavac.Kreiraj;
import javax.swing.JOptionPane;
import model.Prodavac;

/**
 *
 * @author HP
 */
public class GlavnaForma extends javax.swing.JFrame {

    private Prodavac ulogovaniProdavac;
    /**
     * Creates new form GlavnaForma
     */
    
    public GlavnaForma(Prodavac prodavac) {
        this.ulogovaniProdavac = prodavac;
        initComponents();
        postaviPorukuDobrodoslice();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabelKorisnik = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonOdjava = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuDokumenti = new javax.swing.JMenu();
        jMenuIznajmljivanje = new javax.swing.JMenu();
        jMenuItemKreirajIznajmljivanje = new javax.swing.JMenuItem();
        jMenuItemPretraziIznajmljivanje = new javax.swing.JMenuItem();
        jMenuItemPromeniIznajmljivanje = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuProdavac = new javax.swing.JMenu();
        jMenuItemKreirajProdavac = new javax.swing.JMenuItem();
        jMenuItemPretraziProdavac = new javax.swing.JMenuItem();
        jMenuItemPromeniProdavac = new javax.swing.JMenuItem();
        jMenuItemObrisiProdavac = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuKupac = new javax.swing.JMenu();
        jMenuItemKreirajKupac = new javax.swing.JMenuItem();
        jMenuItemPretraziKupac = new javax.swing.JMenuItem();
        jMenuItemPromeniKupac = new javax.swing.JMenuItem();
        jMenuItemObrisiKupac = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuBicikla = new javax.swing.JMenu();
        jMenuItemKreirajBicikla = new javax.swing.JMenuItem();
        jMenuItemPretraziBicikla = new javax.swing.JMenuItem();
        jMenuItemPromeniBicikla = new javax.swing.JMenuItem();
        jMenuItemObrisiBicikla = new javax.swing.JMenuItem();
        jMenuMesto = new javax.swing.JMenu();
        jMenuItemKreirajMesto = new javax.swing.JMenuItem();
        jMenuItemPretraziMesto = new javax.swing.JMenuItem();
        jMenuItemPromeniMesto = new javax.swing.JMenuItem();
        jMenuItemObrisiMesto = new javax.swing.JMenuItem();
        jMenuTerminDezurstva = new javax.swing.JMenu();
        jMenuItemUbaciTermin = new javax.swing.JMenuItem();
        jMenuItemPretraziTermin = new javax.swing.JMenuItem();
        jMenuItemPromeniTermin = new javax.swing.JMenuItem();
        jMenuItemObrisiTermin = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        jMenu7.setText("File");
        jMenuBar1.add(jMenu7);

        jMenu9.setText("Edit");
        jMenuBar1.add(jMenu9);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelKorisnik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelKorisnik.setText("Zdravo, korisnice");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Dobrodošli u aplikaciju za praćenje iznajmljivanja bicikala!");

        jButtonOdjava.setText("ODJAVI SE");
        jButtonOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdjavaActionPerformed(evt);
            }
        });

        jMenuDokumenti.setText("Dokumenti");

        jMenuIznajmljivanje.setText("Iznajmljivanje");

        jMenuItemKreirajIznajmljivanje.setText("Kreiraj");
        jMenuItemKreirajIznajmljivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajIznajmljivanjeActionPerformed(evt);
            }
        });
        jMenuIznajmljivanje.add(jMenuItemKreirajIznajmljivanje);

        jMenuItemPretraziIznajmljivanje.setText("Pretraži");
        jMenuIznajmljivanje.add(jMenuItemPretraziIznajmljivanje);

        jMenuItemPromeniIznajmljivanje.setText("Promeni");
        jMenuIznajmljivanje.add(jMenuItemPromeniIznajmljivanje);

        jMenuDokumenti.add(jMenuIznajmljivanje);

        jMenuBar2.add(jMenuDokumenti);

        jMenu8.setText("Pružalac usluge");

        jMenuProdavac.setText("Prodavac");

        jMenuItemKreirajProdavac.setText("Kreiraj");
        jMenuItemKreirajProdavac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajProdavacActionPerformed(evt);
            }
        });
        jMenuProdavac.add(jMenuItemKreirajProdavac);

        jMenuItemPretraziProdavac.setText("Pretraži");
        jMenuProdavac.add(jMenuItemPretraziProdavac);

        jMenuItemPromeniProdavac.setText("Promeni");
        jMenuProdavac.add(jMenuItemPromeniProdavac);

        jMenuItemObrisiProdavac.setText("Obriši");
        jMenuProdavac.add(jMenuItemObrisiProdavac);

        jMenu8.add(jMenuProdavac);

        jMenuBar2.add(jMenu8);

        jMenu1.setText("Primalac usluge");

        jMenuKupac.setText("Kupac");

        jMenuItemKreirajKupac.setText("Kreiraj");
        jMenuKupac.add(jMenuItemKreirajKupac);

        jMenuItemPretraziKupac.setText("Pretraži");
        jMenuKupac.add(jMenuItemPretraziKupac);

        jMenuItemPromeniKupac.setText("Promeni");
        jMenuKupac.add(jMenuItemPromeniKupac);

        jMenuItemObrisiKupac.setText("Obriši");
        jMenuKupac.add(jMenuItemObrisiKupac);

        jMenu1.add(jMenuKupac);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Šifarnici");

        jMenuBicikla.setText("Bicikla");

        jMenuItemKreirajBicikla.setText("Kreiraj");
        jMenuBicikla.add(jMenuItemKreirajBicikla);

        jMenuItemPretraziBicikla.setText("Pretraži");
        jMenuBicikla.add(jMenuItemPretraziBicikla);

        jMenuItemPromeniBicikla.setText("Promeni");
        jMenuBicikla.add(jMenuItemPromeniBicikla);

        jMenuItemObrisiBicikla.setText("Obriši");
        jMenuBicikla.add(jMenuItemObrisiBicikla);

        jMenu2.add(jMenuBicikla);

        jMenuMesto.setText("Mesto");

        jMenuItemKreirajMesto.setText("Kreiraj");
        jMenuMesto.add(jMenuItemKreirajMesto);

        jMenuItemPretraziMesto.setText("Pretraži");
        jMenuMesto.add(jMenuItemPretraziMesto);

        jMenuItemPromeniMesto.setText("Promeni");
        jMenuMesto.add(jMenuItemPromeniMesto);

        jMenuItemObrisiMesto.setText("Obriši");
        jMenuMesto.add(jMenuItemObrisiMesto);

        jMenu2.add(jMenuMesto);

        jMenuTerminDezurstva.setText("Termin dežurstva");

        jMenuItemUbaciTermin.setText("Ubaci");
        jMenuTerminDezurstva.add(jMenuItemUbaciTermin);

        jMenuItemPretraziTermin.setText("Pretraži");
        jMenuTerminDezurstva.add(jMenuItemPretraziTermin);

        jMenuItemPromeniTermin.setText("Promeni");
        jMenuTerminDezurstva.add(jMenuItemPromeniTermin);

        jMenuItemObrisiTermin.setText("Obriši");
        jMenuTerminDezurstva.add(jMenuItemObrisiTermin);

        jMenu2.add(jMenuTerminDezurstva);

        jMenuBar2.add(jMenu2);

        jMenu3.setText("Podešavanja");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("O programu");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabelKorisnik)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonOdjava)
                .addGap(257, 257, 257))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabelKorisnik)
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(47, 47, 47)
                .addComponent(jButtonOdjava)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdjavaActionPerformed
        String[] options = {"Da", "Ne"};
        int odgovor = JOptionPane.showOptionDialog(
            this,
            "Da li ste sigurni da želite da se odjavite?",
            "Potvrda odjave",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[1]
        );

        if (odgovor == JOptionPane.YES_OPTION) {
            LoginForma loginForma = new LoginForma();
            loginForma.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jButtonOdjavaActionPerformed

    private void jMenuItemKreirajProdavacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajProdavacActionPerformed
        JOptionPane.showMessageDialog(this, "Sistem je kreirao prodavca.", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
        Kreiraj kreirajProdavac = new Kreiraj(ulogovaniProdavac);
        kreirajProdavac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemKreirajProdavacActionPerformed

    private void jMenuItemKreirajIznajmljivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajIznajmljivanjeActionPerformed
        JOptionPane.showMessageDialog(this, "Sistem je kreirao iznajmljivanje.", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
        KreirajIznajmljivanje kreirajProdavac = new KreirajIznajmljivanje(this, true,ulogovaniProdavac);
        kreirajProdavac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemKreirajIznajmljivanjeActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOdjava;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelKorisnik;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuBicikla;
    private javax.swing.JMenu jMenuDokumenti;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemKreirajBicikla;
    private javax.swing.JMenuItem jMenuItemKreirajIznajmljivanje;
    private javax.swing.JMenuItem jMenuItemKreirajKupac;
    private javax.swing.JMenuItem jMenuItemKreirajMesto;
    private javax.swing.JMenuItem jMenuItemKreirajProdavac;
    private javax.swing.JMenuItem jMenuItemObrisiBicikla;
    private javax.swing.JMenuItem jMenuItemObrisiKupac;
    private javax.swing.JMenuItem jMenuItemObrisiMesto;
    private javax.swing.JMenuItem jMenuItemObrisiProdavac;
    private javax.swing.JMenuItem jMenuItemObrisiTermin;
    private javax.swing.JMenuItem jMenuItemPretraziBicikla;
    private javax.swing.JMenuItem jMenuItemPretraziIznajmljivanje;
    private javax.swing.JMenuItem jMenuItemPretraziKupac;
    private javax.swing.JMenuItem jMenuItemPretraziMesto;
    private javax.swing.JMenuItem jMenuItemPretraziProdavac;
    private javax.swing.JMenuItem jMenuItemPretraziTermin;
    private javax.swing.JMenuItem jMenuItemPromeniBicikla;
    private javax.swing.JMenuItem jMenuItemPromeniIznajmljivanje;
    private javax.swing.JMenuItem jMenuItemPromeniKupac;
    private javax.swing.JMenuItem jMenuItemPromeniMesto;
    private javax.swing.JMenuItem jMenuItemPromeniProdavac;
    private javax.swing.JMenuItem jMenuItemPromeniTermin;
    private javax.swing.JMenuItem jMenuItemUbaciTermin;
    private javax.swing.JMenu jMenuIznajmljivanje;
    private javax.swing.JMenu jMenuKupac;
    private javax.swing.JMenu jMenuMesto;
    private javax.swing.JMenu jMenuProdavac;
    private javax.swing.JMenu jMenuTerminDezurstva;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    // End of variables declaration//GEN-END:variables

    private void postaviPorukuDobrodoslice() {
        String ime = ulogovaniProdavac.getIme() + " " + ulogovaniProdavac.getPrezime();  
        jLabelKorisnik.setText("Zdravo, " + ime + "!");
    }
}
